export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const TASK_LOAD_SUCCESS = 'TASK_LOAD_SUCCESS';
export const TASK_LOAD_FAIL = 'TASK_LOAD_FAIL';

export const TASK_CREATE_SUCCESS = 'TASK_CREATE_SUCCESS ';
export const TASK_CREATE_FAIL = 'TASK_CREATE_FAIL';

export const TASK_UPDATE_SUCCESS = 'TASK_UPDATE_SUCCESS ';
export const TASK_UPDATE_FAIL = 'TASK_UPDATE_FAIL';

export const TASK_DELETE_SUCCESS = 'TASK_DELETE_SUCCESS ';
export const TASK_DELETE_FAIL = 'TASK_DELETE_FAIL';
